name: jjump88_GUI_MENU
description: GUI_MENU
version: 1.2.0
author: Chatchayut(jjump88)
main: me.Chatchayut.GUIMenu.Menu

commands:
  menu:
    description: open GUI menu
  givemenu:
    description: give you a new menu

